# Generated by Django 3.0.11 on 2021-03-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='External id'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_bot',
            field=models.BooleanField(blank=True, default=False, verbose_name='Lenguage code'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='lenguage_code',
            field=models.CharField(blank=True, default='en', max_length=255, verbose_name='Lenguage code'),
        ),
    ]
