# Generated by Django 3.0.11 on 2021-04-23 12:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conference', '0006_auto_20210416_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created at')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Updated at')),
                ('external_id', models.CharField(max_length=255, verbose_name='External id')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('type', models.CharField(max_length=255, verbose_name='Type')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('conferences', models.ManyToManyField(related_name='group_channels', to='conference.Conference')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
