# Generated by Django 3.0.11 on 2021-03-26 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created at')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Name of Conference')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserConference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created at')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Updated at')),
                ('slide_position', models.IntegerField(default=1, verbose_name='Slide Position')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_conferences', to='conference.Conference')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_conferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Created at')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Updated at')),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='Text')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('voice', models.CharField(blank=True, max_length=255, null=True, verbose_name='Voice')),
                ('position', models.IntegerField(default=1, verbose_name='Position')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='conference.Conference')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
