# Generated by Django 3.0.11 on 2021-04-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_userconference_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
