# Generated by Django 3.0.11 on 2021-04-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_auto_20210411_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='visible_to_all',
            field=models.BooleanField(default=False),
        ),
    ]
