# Generated by Django 3.0.11 on 2021-05-11 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0006_auto_20210416_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conference.Course'),
        ),
    ]
