# Generated by Django 3.0.11 on 2021-07-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0009_auto_20210606_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='alert_to_owner',
            field=models.BooleanField(default=True),
        ),
    ]
