#!/bin/bash

set -o errexit
set -o nounset

source /app/.venv/bin/activate

celery flower \
    --app=config.celery_app \
    --broker="${CELERY_BROKER_URL}" \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
